"""baseline

Revision ID: 37d6fb9c6e53
Revises: 
Create Date: 2026-05-29 11:23:00.452286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d6fb9c6e53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dingtalk_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('root_dept_id', sa.String(length=50), nullable=True),
    sa.Column('department_count', sa.Integer(), nullable=False),
    sa.Column('remote_user_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dingtalk_user_id', sa.String(length=100), nullable=True),
    sa.Column('dingtalk_union_id', sa.String(length=100), nullable=True),
    sa.Column('dingtalk_dept_ids', sa.String(length=300), nullable=True),
    sa.Column('dingtalk_title', sa.String(length=100), nullable=True),
    sa.Column('dingtalk_mobile_tail', sa.String(length=8), nullable=True),
    sa.Column('dingtalk_active', sa.Boolean(), nullable=True),
    sa.Column('dingtalk_synced_at', sa.DateTime(), nullable=True),
    sa.Column('short_code_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_dingtalk_union_id'), ['dingtalk_union_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_dingtalk_user_id'), ['dingtalk_user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_background_tasks_type'), ['type'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('at_user_id', sa.String(length=100), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('skipped_reason', sa.String(length=100), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_code', sa.String(length=50), nullable=True),
    sa.Column('provider_message', sa.String(length=300), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_label', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))

    op.drop_table('sessions')
    op.drop_table('notification_logs')
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_type'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_created_by'))

    op.drop_table('background_tasks')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_dingtalk_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_dingtalk_union_id'))

    op.drop_table('users')
    op.drop_table('dingtalk_sync_logs')
    # ### end Alembic commands ###
